<?php

namespace Brother\CommentBundle\Admin;

use Brother\CommentBundle\Model\CommentManagerInterface;
use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\CoreBundle\Model\ManagerInterface;

class CommentAdmin extends Admin
{
    /**
     * @var CommentManagerInterface
     */
    protected $commentManager;

    public function __construct($code, $class, $baseControllerName)

    {
        parent::__construct($code, $class, $baseControllerName); // TODO: Change the autogenerated stub
        $this->setTranslationDomain('BrotherCommentBundle');
        }


    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')
            ->add('recordModel')
            ->add('recordId')
            ->add('authorName')
            ->add('authorEmail')
            ->add('authorWebsite')
            ->add('body')
            ->add('editionReason')
            ->add('state')
            ->add('created_at')
            ->add('updated_at')
            ->add('link')
            ->add('isSubscribe')
        ;
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('id')
            ->add('recordModel')
            ->add('recordId')
            ->add('authorName')
            ->add('authorEmail')
            ->add('authorWebsite')
            ->add('body')
            ->add('editionReason')
            ->add('status')
            ->add('created_at')
            ->add('updated_at')
            ->add('link')
            ->add('isSubscribe')
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                    'delete' => array(),
                )
            ))
        ;
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('id')
            ->add('recordModel')
            ->add('recordId')
            ->add('authorName')
            ->add('authorEmail')
            ->add('authorWebsite')
            ->add('body')
            ->add('editionReason')
            ->add('status')
            ->add('created_at')
            ->add('updated_at')
            ->add('link')
            ->add('isSubscribe')
        ;
    }

    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')
            ->add('recordModel')
            ->add('recordId')
            ->add('authorName')
            ->add('authorEmail')
            ->add('authorWebsite')
            ->add('body')
            ->add('editionReason')
            ->add('status')
            ->add('created_at')
            ->add('updated_at')
            ->add('link')
            ->add('isSubscribe')
        ;
    }

    /**
     * @param ManagerInterface $commentManager
     */
    public function setCommentManager(ManagerInterface $commentManager)
    {
        if (!$commentManager instanceof CommentManagerInterface) {
            @trigger_error('Calling the '.__METHOD__.' method with a Sonata\CoreBundle\Model\ManagerInterface is deprecated since version 2.4 and will be removed in 3.0. Use the new signature with a Brother\CommentBundle\Model\CommentManagerInterface instead.', E_USER_DEPRECATED);
        }

        $this->commentManager = $commentManager;
    }

}
